<?php
// translation done by Ulli Heist - http://heist.hobby-site.org/
$labels = array();
$labels['report_junk_buttontitle'] = 'als SPAM melden';
$labels['report_junk_reportedasjunk'] = 'Erfolgreich als SPAM gemeldet';
$labels['report_junk_question'] = 'Mail(s) als SPAM melden?';
$labels['report_junk'] = 'Wollen Sie die markierte(n) Mail(s) bei den folgenden Diensten als Spam melden, um die automatische Spamerkennung zu verbessern?';
$labels['report_junk_personaldata'] = 'Ihre pers&ouml;nlichen Informationen werden vor dem Senden entfernt.';
$labels['report_junk_always'] = 'Immer senden';
$labels['report_junk_once'] = 'Einmalig senden';
$labels['report_junk_no'] = 'Nicht senden';
$labels['report_junk_settingsstored'] = 'Ihre Einstellungen wurden gespeichert.';
$labels['report_junk_reportsgenerated'] = 'Die Nachrichten wurden als SPAM gemeldet.';
$labels['report_junk_reportsfailed'] = 'Nachrichten konnten nicht als SPAM gemeldet werden. Bitte versuchen Sie es sp&auml;ter erneut.';

?>
