<?php

$labels = array();
$labels['report_junk_buttontitle'] = 'Report as Spam';
$labels['report_junk_reportedasjunk'] = 'Successfully reported as Spam';
$labels['report_junk_question'] = 'Report mails as SPAM?';
$labels['report_junk'] = 'Do you want to report the selected mail(s) to the following Spamprotection Services in order to improve automated spamdetection measures?';
$labels['report_junk_personaldata'] = 'Your personal information will be removed from the message before sending.';
$labels['report_junk_always'] = 'Send without asking';
$labels['report_junk_once'] = 'Send once';
$labels['report_junk_no'] = 'Don\'t send';
$labels['report_junk_settingsstored'] = 'Your settings have been stored.';
$labels['report_junk_reportsgenerated'] = 'Your selected mails have been reported as spam.';
$labels['report_junk_reportsfailed'] = 'Messages could not be reported as spam. Please try again later.';

?>
