<?php
// translations done by Stéphane Moureau
$labels = array();
$labels['report_junk_buttontitle'] = 'Signaler comme pourriel';
$labels['report_junk_buttontext'] = 'Pourriel'
$labels['report_junk_reportedasjunk'] = 'Signalement effectué';
$labels['report_junk_question'] = 'Signaler comme pourriels ?';
$labels['report_junk'] = 'Afin d\'améliorer la détection automatique, voulez-vous signaler les courriels sélectionnés à ces services anti-spam ?';
$labels['report_junk_personaldata'] = 'Vos données personnelles seront retirées avant l\'envoi.';
$labels['report_junk_always'] = 'Envoyer sans confirmation';
$labels['report_junk_once'] = 'Envoyer une fois';
$labels['report_junk_no'] = 'Ne pas envoyer';
$labels['report_junk_settingsstored'] = 'Vos réglages ont été rétablis.';
$labels['report_junk_reportsgenerated'] = 'Les courriels sélectionnés ont été signalés comme pourriels.';
$labels['report_junk_reportsfailed'] = 'Signalement impossible actuellement, veuillez essayer plus tard.';

?>
